### PR TITLE
(SIMP-4399) Update test deps in fixtures

### PR DESCRIPTION
**Pull request by lnemsick-simp**
SIMP-4399 # comment pupmod-simp-simp_nfs update test fixtures

### CODE REVIEW

**Comment by jeefberkey** [comment]
🔴 https://gitlab.com/simp/pupmod-simp-simp_nfs/-/jobs/51924052

**Comment by trevor-vaughan** [comment]
@jeefberkey Did you run this one by hand to see if the issue is reproducible?

**Comment by jeefberkey** [comment]
@trevor-vaughan Working on it to see if it's a real error, because it looks like the module is having issues

**Comment by jeefberkey** [comment]
nope ✔️ https://gitlab.com/simp/pupmod-simp-simp_nfs/pipelines/17332743

**Pull request merged**
